// auto-generated from NAMES.txt
var ATTENDEE_LIST = [
"Kevin Kane",
"Chris Mears",
"Jonathan Lane",
"Chris Wilkinson",
"Chris Wilkinson + 1",
"Scott Bateman",
"Ron Myers",
"J.B. Rainsberger",
"Mike Berger",
"Josh Biggley",
"Mark Wright",
"Roy Kressin",
"Jason Wentzel",
"Joab Souza",
"Nolan Phillips",
"Ron MacKay",
"Christian Southgate",
"Christian Southgate + 1",
"Ben",
"Callista Tan",
"Kevin MacPhail",
"Evan Porter",
];
