// auto-generated from NAMES.txt
var ATTENDEE_LIST = [
"Christian S",
"Christian S + 1",
"Scott Gallant",
"Kris Olafson",
"Jahanzaib R",
"Malcolm Hiseman",
"Nolan Phillips",
"Ben",
"Mike Berger",
"Nitheen Rao T",
"Callista Tan",
"Mark Wright",
"Michael G",
"Adam LeBlanc",
"Ross Evans",
"Ross Evans + 1",
"Jordan P",
"Adam McIssac",
"Luke Taylor",
"Neil Mader",
"Cheslea F",
"roy kressin",
"jbrains",
"Christopher VH",
"Michael MacLean",
"Kelvin Liang",
"Kelvin Liang + 1",
"Jarred Kenny",
"Rich MacKinnon",
"Mike MacKay"
];
