// auto-generated from NAMES.txt
var ATTENDEE_LIST = [
"Christian Southgate",
"Ken Williams",
"Dmitrii Shesterkin",
"Chris Mears",
"Krista Gallant-Mears",
"Nicholas Phelan",
"Ross Evans",
"Lincoln Maskey",
"Kevin MacPhail",
"Brent Mitton",
"Nolan Phillips",
"J.B. Rainsberger",
"Ron MacKay",
"Ron Myers",
"Kristen",
"Stirling Giddings",
"Shayne Walker",
"Callista Tan",
"Quinn Jackson",
];